# Generated by Django 3.1.12 on 2026-04-13 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('camera_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrowdAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('camera_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('crowd_count', models.IntegerField(default=0)),
                ('safe_limit', models.IntegerField(default=20)),
                ('density_level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'crowd_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('camera_id', models.CharField(default='Camera-1', max_length=100)),
                ('location', models.CharField(default='Main Entrance', max_length=200)),
                ('total_faces', models.IntegerField(default=0)),
                ('masked_count', models.IntegerField(default=0)),
                ('unmasked_count', models.IntegerField(default=0)),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-timestamp'],
            },
        ),
    ]
